name: Bug Report
description: Create a report to help us improve
labels: bug
body:
  - type: markdown
    attributes:
      value: Thank you for filing a bug report!
  - type: textarea
    id: problem
    attributes:
      label: Summary
      description: >
        Please provide a short summary of the bug, along with any information
        you feel relevant to replicate the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      value: |
        I tried this:

        1. `meshexec`

        I expected this to happen:

        Instead, this happened:
  - type: textarea
    id: meshexec-config
    attributes:
      label: MeshExec configuration
      description: Include the configuration file you used when running the server to help diagnose the issue
  - type: textarea
    id: meshexec-log
    attributes:
      label: MeshExec log
      description: Include the MeshExec log file to help diagnose the issue.
      value: |
        | OS      | Log file location                                     |
        | ------- | ----------------------------------------------------- |
        | Linux   | `~/.cache/meshexec/meshexec.log`                      |
        | Mac     | `~/Library/Logs/meshexec/meshexec.log`                |
        | Windows | `C:\Users\<User>\AppData\Local\meshexec\meshexec.log` |

        ```
        please provide a copy of your meshexec log file here if possible; you may need to redact some of the lines
        ```

  - type: input
    id: platform
    attributes:
      label: Platform
      placeholder: Linux / macOS / Windows
    validations:
      required: true
  - type: input
    id: meshexec-version
    attributes:
      label: MeshExec Version
      description: >
        MeshExec version (`meshexec --version` if using a release, `git describe` if building
        from main).
        **Make sure that you are using the [latest meshexec release](https://github.com/Dark-Alex-17/meshexec/releases) or a newer main build**
      placeholder: "meshexec 0.1.0"
    validations:
      required: true
